package com.example.api_agent_service.ReviewProject;
import lombok.*;

@Data
public class Review {

    private int id;
    private String productName;
    private String title;
    private String content;
    private String date;
    private String gpt_answer;

    //Constructors, getters, and setters are generated by Lombok annotations.
    //@SuppressWarnings("unused")
    public Review(String productName, String title, String content, String date, String gpt_answer) {
        this.productName = productName;
        this.title = title;
        this.content = content;
        this.date = date;
        this.gpt_answer = gpt_answer;

    }

}
